apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cqou99lbl-python 
  janus-idp.io/tekton: cqou99lbl-python
  backstage.io/kubernetes-id: cqou99lbl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cqou99lbl-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml