apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cqou99lbl-python-gitops
  description: This is GitOps manifest for cqou99lbl-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=cqou99lbl-python
    backstage.io/kubernetes-id: cqou99lbl-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/cqou99lbl-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:cqou99lbl-python
