apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cqou99lbl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cqou99lbl-python 
  name: cqou99lbl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cqou99lbl-python 
